kgs:
  key:
    length: 6

app:
  host: "localhost:8080"

  schedule:
    cron:
      expired_bins: "0 0 * * * *" # Every 1hr
      generate_keys: "0 0 0,12 * * *" # every 12am/pm

    config:
      max_inactive_keys: 200
